seed: 42
deterministic : true
device:
  type: "cpu"             # Options: "auto", "cuda", "cpu"
  force_cpu: True         # Set to true to force CPU even if CUDA is available

# Paths will be resolved dynamically relative to project root
work_dir: ./experiments/runs/
exp_name: OWV_test3

# Data
data:
  name: VG150             # VG150 | VRD
  root: ./dataset/vg150
  images_dir: images
  ann_dir: annotations/vg150_clean.json   
  dedup_iou: 0.95
  # augment:
  #   random_flip: true
  #   color_jitter: false
    
# Model / Algo:
model: "configs/model/vit_detector.yaml"
algo:  "configs/algo/algo_default.yaml"


# Training
train:
  total_steps: 1000
  log_every: 10
  eval_every: 200
  ckpt_every: 50
  grad_clip_norm: 1.0  
  batch_size: 14          
  num_workers: 1           # set 4 for GPU